export const types = {
  //[Dentist]
  GET_DENTIST: 'GET_DENTIST',
  GET_DENTIST_ID: 'GET_DENTIST_ID',
  ERROR_DENTIST: 'ERROR_DENTIST',

  //[Favorite]
  SET_FAVORITE: 'SET_FAVORITE',
  REMOVE_ALL_FAVORITES: 'REMOVE_ALL_FAVORITES',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',

  //[Theme]
  TOGGLE_THEME: '[Dark_Mode] TOGGLE_THEME',
};